image: archlinux
packages:
  - nodejs
  - npm
secrets:
  - 1073e969-9be9-4809-aac2-076b39494398 # deploy key
sources:
  - https://github.com/clonkspot/frontend

tasks:
  - build: |
      cd frontend
      npm install
      npm run build
  - test: |
      cd frontend
      npm run test
      [[ "$GITHUB_REF" = refs/heads/master ]] || complete-build
  - deploy: |
      ssh -o StrictHostKeyChecking=no clonkspot@clonkspot.org deploy/frontend.sh
